
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS expenses CASCADE;
DROP TABLE IF EXISTS students CASCADE;
DROP TABLE IF EXISTS groups CASCADE;

DROP FUNCTION IF EXISTS get_student_group(UUID);
DROP FUNCTION IF EXISTS get_student_payments(UUID);
